# VAC – Data Cleaning with Pandas
## B.Tech CSE | 3-Hour Hands-on Session

**Trainer objective:** By the end of this session, students should be able to take a genuinely messy student dataset and convert it into a clean, analysis-ready DataFrame.

### Dataset
- ~50,400 rows including intentional duplicate records
- Mixed data types
- Missing values represented in different ways
- Inconsistent column names
- Extra spaces and inconsistent capitalization
- Duplicate records
- Invalid ages, marks and salaries
- Inconsistent city/department/course names
- Dirty email and phone values
- Mixed/invalid date formats
- Out-of-range attendance/marks

**Important:** Do not jump directly to the final solution. First inspect the problem, then clean it step by step.

## 3-Hour Training Roadmap

**0:00–0:20 — Understand the dataset**
- Load data
- `head()`, `tail()`, `shape`, `info()`, `describe()`
- Find columns and data types

**0:20–0:45 — Column cleaning**
- Rename columns
- Standardize column names
- Remove unwanted spaces

**0:45–1:20 — Missing values**
- Detect missing values
- Understand `NaN`, empty strings and text placeholders
- Replace placeholders with real missing values
- Decide when to drop vs fill

**1:20–1:50 — Duplicates + text cleaning**
- Detect/remove duplicates
- Clean names, cities, departments and courses
- Standardize categories

**1:50–2:25 — Data type + invalid value cleaning**
- Convert age, marks, salary and attendance
- Detect impossible values
- Handle invalid phone/email values

**2:25–2:50 — Date cleaning + validation**
- Parse mixed dates
- Check ranges and consistency
- Create useful derived columns

**2:50–3:00 — Final student challenge**
- Clean the full dataset independently

## Step 1 – Import Libraries and Load the Messy Dataset

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

df = pd.read_csv("messy_btech_student_data_50k.csv")

print("Rows and columns:", df.shape)
df.head()

Rows and columns: (50400, 13)

,Student Name,EMAIL Address,Age (yrs),Gender,City/Location,Department Name,Course,Marks %,Annual Salary,Phone Number,Admission Date,Attendance %,Student_ID
0,Priya Mehta,priya.mehta872@example.com,22.0,male,Delhi,CSE,M.Tech,84.4,40885.0,9829425658,2023-01-18,89.7,STU-145078
1,Karan Tiwari,karan.tiwari834@gmail.com,21.0,FEMALE,Gurgaon,ECE,M.Tech,90.6,57758.0,9784662806,2024-01-06,78.6,STU-136590
2,Diya Chauhan,diya.chauhan357@outlook.com,19.0,NaN,Mumbai,cse,B.Sc,91.4,41814.0,9409801075,2022-10-12,NaN,STU-109430
3,Rahul Yadav,rahul.yadav260@outlook.com,22.0,Other,MUMBAI,Electronics,BTECH,60.0,29242.0,9387127009,2022-01-28,91.3,STU-107096
4,Ishita Chauhan,ishita.chauhan303@example.com,16.0,male,Pune,Data Science,B.Tech,65.6,61316.0,9680501786,2023-04-09,91.0,STU-120418

## Step 2 – First Inspection

In [2]:
print("Shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nBasic information:")
df.info()

Shape: (50400, 13)

Column names:
['Student Name', 'EMAIL Address', 'Age (yrs)', 'Gender ', 'City/Location', 'Department Name', 'Course', 'Marks %', 'Annual Salary', 'Phone Number', 'Admission Date', 'Attendance %', 'Student_ID']

Data types:
Student Name       object
EMAIL Address      object
Age (yrs)          object
Gender             object
City/Location      object
Department Name    object
Course             object
Marks %            object
Annual Salary      object
Phone Number       object
Admission Date     object
Attendance %       object
Student_ID         object
dtype: object

Basic information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50400 entries, 0 to 50399
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Student Name     50400 non-null  object
 1   EMAIL Address    49084 non-null  object
 2   Age (yrs)        49490 non-null  object
 3   Gender           44256 non-null  object
 4   City/Location    49236 non-null  object
 5   Department Name  49480 non-null  object
 6   Course           50400 non-null  object
 7   Marks %          49278 non-null  object
 8   Annual Salary    49382 non-null  object
 9   Phone Number     48888 non-null  object
 10  Admission Date   48381 non-null  object
 11  Attendance %     49640 non-null  object
 12  Student_ID       50400 non-null  object
dtypes: object(13)
memory usage: 5.0+ MB

In [3]:
df.head(10)

,Student Name,EMAIL Address,Age (yrs),Gender,City/Location,Department Name,Course,Marks %,Annual Salary,Phone Number,Admission Date,Attendance %,Student_ID
0,Priya Mehta,priya.mehta872@example.com,22.0,male,Delhi,CSE,M.Tech,84.4,40885.0,9829425658,2023-01-18,89.7,STU-145078
1,Karan Tiwari,karan.tiwari834@gmail.com,21.0,FEMALE,Gurgaon,ECE,M.Tech,90.6,57758.0,9784662806,2024-01-06,78.6,STU-136590
2,Diya Chauhan,diya.chauhan357@outlook.com,19.0,NaN,Mumbai,cse,B.Sc,91.4,41814.0,9409801075,2022-10-12,NaN,STU-109430
3,Rahul Yadav,rahul.yadav260@outlook.com,22.0,Other,MUMBAI,Electronics,BTECH,60.0,29242.0,9387127009,2022-01-28,91.3,STU-107096
4,Ishita Chauhan,ishita.chauhan303@example.com,16.0,male,Pune,Data Science,B.Tech,65.6,61316.0,9680501786,2023-04-09,91.0,STU-120418
5,Pooja Jain,pooja.jain483@yahoo.com,20.0,male,Pune,Electronics,M.Tech,60.3,22972.0,9865084113,2022-02-09,85.3,STU-103767
6,Rahul Kumar,rahul.kumar296@yahoo.com,22.0,male,Chennai,ECE,b.tech,96.0,76301.0,9178474224,2023-10-07,78.8,STU-114164
7,Kavya Singh,kavya.singh500@gmail.com,21.0,Other,MUMBAI,ME,B.tech,68.3,33537.0,12345,2024-10-21,76.5,STU-148071
8,KAVYA MALHOTRA,kavya.malhotra766@outlook.com,17.0,unknown,MUMBAI,IT,M.Tech,71.9,53109.0,9619441114,2024-11-01,68.5,STU-120628
9,Rohan Gupta,rohan.gupta908@example.com,22.0,MALE,Noida,ECE,BCA,76.1,58167.0,9210397096,2022-02-19,100.0,STU-100508

In [4]:
df.describe(include="all").T

                 count unique           top  freq
Student Name     50400    959  Ishita Patel   187
EMAIL Address    49084  46871  not-an-email   486
Age (yrs)        49490     21          21.0  7826
Gender           44256     11       unknown  4770
City/Location    49236     21     Bengaluru  2675
Department Name  49480     13            ME  4611
Course           50400      7         BTECH  7275
Marks %          49278    798         100.0  1031
Annual Salary    49382  31444       unknown   168
Phone Number     48888  47507         12345   517
Admission Date   48381   1208    2023-07-15   805
Attendance %     49640    676         100.0  2792
Student_ID       50400  50000    STU-143754     2

## Step 3 – Rename the Columns

### Student Task
The current names are inconsistent:
- spaces
- brackets
- mixed capitalization
- slash characters

Create clean, programming-friendly column names using **lowercase + underscore**.

Target style:

`student_name`, `email`, `age`, `gender`, `city`, `department`, `course`, `marks`, `annual_salary`, `phone`, `admission_date`, `attendance`, `student_id`

### Trainer Solution

In [5]:
df.rename(columns={
    "Student Name": "student_name",
    "EMAIL Address": "email",
    "Age (yrs)": "age",
    "Gender ": "gender",
    "City/Location": "city",
    "Department Name": "department",
    "Course": "course",
    "Marks %": "marks",
    "Annual Salary": "annual_salary",
    "Phone Number": "phone",
    "Admission Date": "admission_date",
    "Attendance %": "attendance",
    "Student_ID": "student_id"
}, inplace=True)

df.columns

Index(['student_name', 'email', 'age', 'gender', 'city', 'department',
       'course', 'marks', 'annual_salary', 'phone', 'admission_date',
       'attendance', 'student_id'],
      dtype='object')

## Step 4 – Detect Missing Values

First calculate missing values with Pandas.

Then notice that some missing values are not actually stored as `NaN`. Values such as `NA`, `N/A`, `null`, empty strings and `Not Available` are also present.

### Student Task
Find:
- missing count per column
- missing percentage per column

In [6]:
missing_count = df.isna().sum()
missing_percent = (df.isna().mean() * 100).round(2)

missing_report = pd.DataFrame({
    "missing_count": missing_count,
    "missing_percent": missing_percent
}).sort_values("missing_percent", ascending=False)

missing_report

                missing_count  missing_percent
gender                   6144            12.19
admission_date           2019             4.01
phone                    1512             3.00
email                    1316             2.61
city                     1164             2.31
marks                    1122             2.23
annual_salary            1018             2.02
department                920             1.83
age                       910             1.81
attendance                760             1.51
student_name                0             0.00
course                      0             0.00
student_id                  0             0.00

### Standardize Missing-Value Tokens

In [12]:
missing_tokens = ["", "NA", "N/A", "null", "Not Available", "unknown"]

df = df.replace(missing_tokens, np.nan)

print("Total missing values:", df.isna().sum().sum())
df.isna().sum().sort_values(ascending=False)

Total missing values: 11283

admission_date    2453
phone             1996
email             1760
marks             1513
annual_salary     1322
age               1220
attendance        1019
student_name         0
gender               0
city                 0
course               0
department           0
student_id           0
dtype: int64

## Step 5 – Decide How to Handle Missing Values

There is no single rule: the decision depends on the column.

For this dataset:
- `email` → keep missing if unavailable
- `phone` → keep missing if unavailable
- `gender`, `city`, `department` → fill with `"Unknown"`
- `age`, `marks`, `attendance` → use a sensible numeric strategy
- `annual_salary` → median is safer than mean when outliers exist
- `admission_date` → keep missing if it cannot be recovered

In [56]:
# Convert numeric columns to numeric data type
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df["marks"] = pd.to_numeric(df["marks"], errors="coerce")
df["attendance"] = pd.to_numeric(df["attendance"], errors="coerce")
df["annual_salary"] = pd.to_numeric(df["annual_salary"], errors="coerce")

In [32]:
for col in ["gender", "city", "department", "course"]:
    df[col] = df[col].fillna("Unknown")

df["age"] = df["age"].fillna(df["age"].median())
df["marks"] = df["marks"].fillna(df["marks"].median())
df["attendance"] = df["attendance"].fillna(df["attendance"].median())
df["annual_salary"] = df["annual_salary"].fillna(df["annual_salary"].median())

df.isna().sum()

student_name         0
email             3410
age                  0
gender               0
city                 0
department           0
course               0
marks                0
annual_salary        0
phone             2495
admission_date    6093
attendance           0
student_id           0
dtype: int64

## Step 6 – Remove Extra Spaces and Standardize Text

A common real-world problem is that:

`Delhi`, ` Delhi`, `DELHI`, `delhi `

may represent the same category.

### Student Task
Clean the string columns using:
- `.str.strip()`
- `.str.lower()`

Then standardize known category variations.

In [33]:
text_columns = ["student_name", "email", "gender", "city", "department", "course"]

for col in text_columns:
    df[col] = df[col].astype("string").str.strip()

# Make selected categories lowercase for easier standardization
for col in ["gender", "city", "department", "course"]:
    df[col] = df[col].str.lower()

df[["student_name", "gender", "city", "department", "course"]].head(10)

     student_name   gender      city    department  course
0     Priya Mehta     male     delhi           cse  m.tech
1    Karan Tiwari   female  gurugram           ece  m.tech
2    Diya Chauhan  unknown    mumbai           cse    b.sc
3     Rahul Yadav    other    mumbai           ece   btech
4  Ishita Chauhan     male      pune  data science   btech
5      Pooja Jain     male      pune           ece  m.tech
6     Rahul Kumar     male   chennai           ece   btech
7     Kavya Singh    other    mumbai            me   btech
8  KAVYA MALHOTRA  unknown    mumbai            it  m.tech
9     Rohan Gupta     male     noida           ece     bca

In [34]:
# Standardize category names
df["city"] = df["city"].replace({
    "bangalore": "bengaluru",
    "gurgaon": "gurugram"
})

df["department"] = df["department"].replace({
    "computer science": "cse",
    "information technology": "it",
    "electronics": "ece",
    "data science": "data science",
    "mechanical": "me"
})

df["course"] = df["course"].str.replace(" ", "", regex=False).str.lower()
df["course"] = df["course"].replace({
    "b.tech": "btech",
    "btech": "btech"
})

df[["city", "department", "course"]].value_counts().head(20)

city       department    course
bengaluru  cse           btech     1173
gurugram   cse           btech      795
bengaluru  it            btech      778
           me            btech      773
           ece           btech      773
           data science  btech      764
mumbai     cse           btech      748
delhi      cse           btech      747
pune       cse           btech      742
gurugram   me            btech      569
mumbai     me            btech      559
pune       me            btech      550
           ece           btech      545
gurugram   it            btech      538
pune       it            btech      537
delhi      me            btech      532
mumbai     it            btech      522
delhi      data science  btech      521
gurugram   ece           btech      516
mumbai     data science  btech      509
Name: count, dtype: int64

## Step 7 – Find and Remove Duplicate Records

### Student Task
1. Find the number of completely duplicated rows.
2. Remove them.
3. Check the shape again.

Then discuss: **Is every repeated student name necessarily a duplicate?** No. We need a business key such as `student_id`.

In [1]:
duplicate_count = df.duplicated().sum()
print("Duplicate rows:", duplicate_count)

NameError: name 'df' is not defined

In [36]:
df.drop_duplicates(inplace=True)

print("New shape:", df.shape)
print("Duplicates remaining:", df.duplicated().sum())

New shape: (50000, 13)
Duplicates remaining: 0

## Step 8 – Clean Numeric Columns

The columns `age`, `marks`, `annual_salary`, and `attendance` may contain invalid values.

### Business rules
- Age should be between **17 and 35**
- Marks should be between **0 and 100**
- Attendance should be between **0 and 100**
- Salary should be greater than **0**

### Student Task
Identify invalid values first. Do not blindly delete rows.

In [37]:
numeric_cols = ["age", "marks", "annual_salary", "attendance"]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[numeric_cols].describe())

                age         marks  annual_salary    attendance
count  50000.000000  50000.000000   5.000000e+04  50000.000000
mean      20.823560     67.759770   6.959630e+04     77.640834
std        2.137307     15.316471   5.169294e+05     13.171560
min       17.000000     20.000000   8.417000e+03     30.000000
25%       19.000000     57.500000   3.201975e+04     68.800000
50%       21.000000     67.900000   4.010900e+04     78.000000
75%       22.000000     78.100000   5.075800e+04     87.100000
max       30.000000    100.000000   9.999999e+06    100.000000

In [39]:
# Trainer solution: convert impossible values to NaN
df.loc[~df["age"].between(17, 35), "age"] = np.nan
df.loc[~df["marks"].between(0, 100), "marks"] = np.nan
df.loc[df["annual_salary"] <= 0, "annual_salary"] = np.nan
df.loc[~df["attendance"].between(0, 100), "attendance"] = np.nan

# Refill values after invalid records were converted to NaN
df["age"] = df["age"].fillna(df["age"].median())
df["marks"] = df["marks"].fillna(df["marks"].median())
df["annual_salary"] = df["annual_salary"].fillna(df["annual_salary"].median())
df["attendance"] = df["attendance"].fillna(df["attendance"].median())

## Step 9 – Clean Email and Phone Numbers

### Email
A basic validation rule for this class:
- must contain `@`
- must contain `.`
- no spaces

### Phone
For this exercise, Indian student phone numbers should contain exactly **10 digits** and start with `6`, `7`, `8`, or `9`.

Do not build a perfect production validator yet. The goal is to understand cleaning logic.

In [40]:
# Email cleaning
df["email"] = df["email"].str.strip().str.lower()

invalid_email = ~df["email"].str.match(r"^[^\s@]+@[^\s@]+\.[^\s@]+$", na=False)
print("Invalid emails:", invalid_email.sum())

df.loc[invalid_email, "email"] = np.nan

# Phone cleaning: remove spaces, hyphens and other non-digit characters
df["phone"] = df["phone"].astype("string").str.replace(r"\D", "", regex=True)

invalid_phone = ~df["phone"].str.match(r"^[6-9]\d{9}$", na=False)
print("Invalid phones:", invalid_phone.sum())

df.loc[invalid_phone, "phone"] = np.nan

Invalid emails: 3410
Invalid phones: 2495

## Step 10 – Clean Dates

The admission date contains several formats and some invalid values.

### Student Task
Convert `admission_date` into a proper Pandas datetime column.

Use:
`pd.to_datetime(..., errors="coerce", dayfirst=...)`

Then inspect how many dates could not be converted.

In [41]:
# Try converting the mixed date column
df["admission_date"] = pd.to_datetime(
    df["admission_date"],
    errors="coerce",
    dayfirst=True
)

print("Missing/invalid dates:", df["admission_date"].isna().sum())
print(df["admission_date"].head(10))

Missing/invalid dates: 6093
0   2023-01-18
1   2024-01-06
2   2022-10-12
3   2022-01-28
4   2023-04-09
5   2022-02-09
6   2023-10-07
7   2024-10-21
8   2024-11-01
9   2022-02-19
Name: admission_date, dtype: datetime64[ns]

## Step 11 – Final Validation

A cleaned dataset is not finished until we validate it.

### Student checklist
Check:
- shape
- duplicate count
- missing values
- data types
- age range
- marks range
- attendance range
- salary validity
- email validity
- phone validity
- category consistency

In [42]:
print("Final shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())

print("\nMissing values:")
print(df.isna().sum().sort_values(ascending=False))

print("\nData types:")
print(df.dtypes)

print("\nNumeric summary:")
print(df[["age", "marks", "annual_salary", "attendance"]].describe())

Final shape: (50000, 13)
Duplicate rows: 0

Missing values:
admission_date    6093
email             3410
phone             2495
student_name         0
age                  0
city                 0
gender               0
department           0
course               0
annual_salary        0
marks                0
attendance           0
student_id           0
dtype: int64

Data types:
student_name      string[python]
email             string[python]
age                      float64
gender            string[python]
city              string[python]
department        string[python]
course            string[python]
marks                    float64
annual_salary            float64
phone             string[python]
admission_date    datetime64[ns]
attendance               float64
student_id                object
dtype: object

Numeric summary:
                age         marks  annual_salary    attendance
count  50000.000000  50000.000000   5.000000e+04  50000.000000
mean      20.823560     67.759770   6.959630e+04     77.640834
std        2.137307     15.316471   5.169294e+05     13.171560
min       17.000000     20.000000   8.417000e+03     30.000000
25%       19.000000     57.500000   3.201975e+04     68.800000
50%       21.000000     67.900000   4.010900e+04     78.000000
75%       22.000000     78.100000   5.075800e+04     87.100000
max       30.000000    100.000000   9.999999e+06    100.000000

In [25]:
print("Cities:")
print(sorted(df["city"].dropna().unique()))

print("\nDepartments:")
print(sorted(df["department"].dropna().unique()))

print("\nCourses:")
print(sorted(df["course"].dropna().unique()))

Cities:
['bengaluru', 'chennai', 'delhi', 'gurugram', 'gwalior', 'hyderabad', 'indore', 'jaipur', 'kolkata', 'lucknow', 'mumbai', 'noida', 'pune', 'unknown']

Departments:
['cse', 'data science', 'ece', 'it', 'me', 'unknown']

Courses:
['b.sc', 'bca', 'btech', 'm.tech']

# Final 10-Minute Student Challenge

## Clean the dataset independently

Create a new variable called `clean_df` and perform the complete cleaning pipeline without copying the trainer solution.

### Minimum requirements
- [ ] Rename all columns
- [ ] Standardize missing-value tokens
- [ ] Measure missing values
- [ ] Handle missing categorical values
- [ ] Handle missing numeric values
- [ ] Strip whitespace
- [ ] Standardize text categories
- [ ] Remove duplicate rows
- [ ] Convert numeric columns
- [ ] Fix invalid age
- [ ] Fix invalid marks
- [ ] Fix invalid attendance
- [ ] Fix invalid salary
- [ ] Validate email
- [ ] Validate phone
- [ ] Convert admission date
- [ ] Run final validation

### Deliverable
Your final DataFrame should be analysis-ready and saved as:

`clean_btech_student_data.csv`

In [43]:
# FINAL STUDENT SUBMISSION CELL

clean_df = df.copy()

# Complete your full cleaning pipeline above, then uncomment:
clean_df.to_csv("clean_btech_student_data1.csv", index=False)

# Show final result:
clean_df.head()

,student_name,email,age,gender,city,department,course,marks,annual_salary,phone,admission_date,attendance,student_id
0,Priya Mehta,priya.mehta872@example.com,22.0,male,delhi,cse,m.tech,84.4,40885.0,9829425658,2023-01-18,89.7,STU-145078
1,Karan Tiwari,karan.tiwari834@gmail.com,21.0,female,gurugram,ece,m.tech,90.6,57758.0,9784662806,2024-01-06,78.6,STU-136590
2,Diya Chauhan,diya.chauhan357@outlook.com,19.0,unknown,mumbai,cse,b.sc,91.4,41814.0,9409801075,2022-10-12,78.0,STU-109430
3,Rahul Yadav,rahul.yadav260@outlook.com,22.0,other,mumbai,ece,btech,60.0,29242.0,9387127009,2022-01-28,91.3,STU-107096
4,Ishita Chauhan,ishita.chauhan303@example.com,21.0,male,pune,data science,btech,65.6,61316.0,9680501786,2023-04-09,91.0,STU-120418

In [44]:
clean_df1 = df.copy()

# Complete your full cleaning pipeline above, then uncomment:
clean_df1.to_csv("clean_btech_student_data11.csv", index=False)

# Show final result:
clean_df1.head()

,student_name,email,age,gender,city,department,course,marks,annual_salary,phone,admission_date,attendance,student_id
0,Priya Mehta,priya.mehta872@example.com,22.0,male,delhi,cse,m.tech,84.4,40885.0,9829425658,2023-01-18,89.7,STU-145078
1,Karan Tiwari,karan.tiwari834@gmail.com,21.0,female,gurugram,ece,m.tech,90.6,57758.0,9784662806,2024-01-06,78.6,STU-136590
2,Diya Chauhan,diya.chauhan357@outlook.com,19.0,unknown,mumbai,cse,b.sc,91.4,41814.0,9409801075,2022-10-12,78.0,STU-109430
3,Rahul Yadav,rahul.yadav260@outlook.com,22.0,other,mumbai,ece,btech,60.0,29242.0,9387127009,2022-01-28,91.3,STU-107096
4,Ishita Chauhan,ishita.chauhan303@example.com,21.0,male,pune,data science,btech,65.6,61316.0,9680501786,2023-04-09,91.0,STU-120418

# Optional Extension – Prepare Data for Analysis

Once the data is clean, create:
1. `admission_year`
2. `admission_month`
3. `performance_category`
4. `attendance_category`

Example:
- marks >= 75 → Excellent
- marks >= 60 → Good
- marks >= 40 → Average
- below 40 → Needs Improvement

This connects **Data Cleaning → Feature Creation → Data Analysis → Data Visualization**.

In [46]:
df2 =  pd.read_csv("clean_btech_student_data11.csv")

In [48]:
df2.columns

Index(['student_name', 'email', 'age', 'gender', 'city', 'department',
       'course', 'marks', 'annual_salary', 'phone', 'admission_date',
       'attendance', 'student_id'],
      dtype='object')

In [49]:
df2["age"] =  df["age"].astype(int)

In [52]:
df2["age"] = df["age"].astype("Int64")
df2.head()

,student_name,email,age,gender,city,department,course,marks,annual_salary,phone,admission_date,attendance,student_id
0,Priya Mehta,priya.mehta872@example.com,22,male,delhi,cse,m.tech,84.4,40885.0,9.829426e+09,2023-01-18,89.7,STU-145078
1,Karan Tiwari,karan.tiwari834@gmail.com,21,female,gurugram,ece,m.tech,90.6,57758.0,9.784663e+09,2024-01-06,78.6,STU-136590
2,Diya Chauhan,diya.chauhan357@outlook.com,19,unknown,mumbai,cse,b.sc,91.4,41814.0,9.409801e+09,2022-10-12,78.0,STU-109430
3,Rahul Yadav,rahul.yadav260@outlook.com,22,other,mumbai,ece,btech,60.0,29242.0,9.387127e+09,2022-01-28,91.3,STU-107096
4,Ishita Chauhan,ishita.chauhan303@example.com,21,male,pune,data science,btech,65.6,61316.0,9.680502e+09,2023-04-09,91.0,STU-120418

# Trainer Note

The teaching principle for this session is:

**Inspect → Identify → Decide → Clean → Validate**

Do not teach cleaning as a list of Pandas commands. Ask students **why** a value is dirty and **what business rule** should be used to fix it.

The same approach works for customer data, sales data, HR data, healthcare data and almost every real-world dataset.

In [54]:
final_copy = df2.copy()

# Complete your full cleaning pipeline above, then uncomment:
final_copy.to_csv("this_is_final_and_clean.csv", index=False)

# Show final result:
final_copy.head()

,student_name,email,age,gender,city,department,course,marks,annual_salary,phone,admission_date,attendance,student_id
0,Priya Mehta,priya.mehta872@example.com,22,male,delhi,cse,m.tech,84.4,40885.0,9.829426e+09,2023-01-18,89.7,STU-145078
1,Karan Tiwari,karan.tiwari834@gmail.com,21,female,gurugram,ece,m.tech,90.6,57758.0,9.784663e+09,2024-01-06,78.6,STU-136590
2,Diya Chauhan,diya.chauhan357@outlook.com,19,unknown,mumbai,cse,b.sc,91.4,41814.0,9.409801e+09,2022-10-12,78.0,STU-109430
3,Rahul Yadav,rahul.yadav260@outlook.com,22,other,mumbai,ece,btech,60.0,29242.0,9.387127e+09,2022-01-28,91.3,STU-107096
4,Ishita Chauhan,ishita.chauhan303@example.com,21,male,pune,data science,btech,65.6,61316.0,9.680502e+09,2023-04-09,91.0,STU-120418

In [55]:
final_copy.shape

(50000, 13)

In [58]:
final_copy.isna().sum()

student_name         0
email             3410
age                394
gender               0
city                 0
department           0
course               0
marks                0
annual_salary        0
phone             2495
admission_date    6093
attendance           0
student_id           0
dtype: int64

In [67]:
final_copy.loc[final_copy["email"].isna(), ["student_name", "email"]]

         student_name email
45        Arjun Gupta   NaN
57        ROHAN KUMAR   NaN
60       Ananya Singh   NaN
63         Neha Verma   NaN
64     Arjun Malhotra   NaN
...               ...   ...
49912   Arjun Agarwal   NaN
49934   Aditya Sharma   NaN
49952     Rahul Patel   NaN
49956   Neha Malhotra   NaN
49969     Kavya Verma   NaN

[3410 rows x 2 columns]

In [68]:
missing_details = final_copy[final_copy.isna().any(axis=1)]

missing_details

,student_name,email,age,gender,city,department,course,marks,annual_salary,phone,admission_date,attendance,student_id
7,Kavya Singh,kavya.singh500@gmail.com,21,other,mumbai,me,btech,68.3,33537.0,NaN,2024-10-21,76.5,STU-148071
34,Neha Yadav,neha.yadav735@gmail.com,24,female,gurugram,cse,btech,88.6,73038.0,NaN,NaN,98.7,STU-137025
37,Kavya Chauhan,kavya.chauhan585@gmail.com,20,female,mumbai,data science,btech,64.9,34808.0,9.763316e+09,NaN,83.6,STU-120524
40,Arjun Singh,arjun.singh548@gmail.com,26,male,hyderabad,ece,bca,54.5,51291.0,9.946277e+09,NaN,99.6,STU-125729
44,Rahul Mishra,rahul.mishra672@outlook.com,17,female,kolkata,data science,b.sc,54.7,33812.0,9.236443e+09,NaN,79.3,STU-130757
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49982,Rohan Chauhan,rohan.chauhan671@gmail.com,21,female,noida,data science,bca,65.5,32272.0,9.891818e+09,NaN,68.9,STU-137819
49993,Ananya Patel,ananya.patel401@gmail.com,23,female,gurugram,ece,btech,80.8,35119.0,9.670413e+09,NaN,87.7,STU-116850
49995,Nisha Jain,nisha.jain748@example.com,21,female,mumbai,cse,bca,81.7,33042.0,NaN,NaN,81.9,STU-111284
49997,Simran Malhotra,simran.malhotra779@example.com,20,unknown,noida,cse,btech,65.0,39299.0,9.364594e+09,NaN,73.9,STU-138158
49998,Rahul Gupta,rahul.gupta38@outlook.com,20,unknown,delhi,ece,btech,58.2,42165.0,NaN,2022-03-29,100.0,STU-100860

In [70]:
final_copy.loc[final_copy["student_id"] == "STU-148071"]

,student_name,email,age,gender,city,department,course,marks,annual_salary,phone,admission_date,attendance,student_id
7,Kavya Singh,kavya.singh500@gmail.com,21,other,mumbai,me,btech,68.3,33537.0,NaN,2024-10-21,76.5,STU-148071

In [62]:
# df.loc[df["student_id"] == "STU-148071", 
       # ["phone", "email", "age"]] = ["9876543210", "kavya.singh500@gmail.com", 21] for multiple

In [73]:
final_copy.loc[final_copy["student_id"] == "STU-148071", "phone"] = "9876543210"

C:\Users\dell\AppData\Local\Temp\ipykernel_18472\2113020102.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '9876543210' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  final_copy.loc[final_copy["student_id"] == "STU-148071", "phone"] = "9876543210"

In [74]:
final_copy.loc[final_copy["student_id"] == "STU-148071"]

,student_name,email,age,gender,city,department,course,marks,annual_salary,phone,admission_date,attendance,student_id
7,Kavya Singh,kavya.singh500@gmail.com,21,other,mumbai,me,btech,68.3,33537.0,9876543210,2024-10-21,76.5,STU-148071

In [65]:
# df.loc[df["student_id"] == "STU-148071" , "gender"]="Fe

In [75]:
final_copy.loc[final_copy["student_id"]== "STU-148071","gender"]="Female"

In [76]:
final_copy.loc[final_copy["student_id"] == "STU-148071"]

,student_name,email,age,gender,city,department,course,marks,annual_salary,phone,admission_date,attendance,student_id
7,Kavya Singh,kavya.singh500@gmail.com,21,Female,mumbai,me,btech,68.3,33537.0,9876543210,2024-10-21,76.5,STU-148071